language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

script:
    - vendor/bin/phpunit --coverage-clover=clover.xml

after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose --config .coveralls.yml
