language: php

php:
  - 7.4
  - 8.0

before_install:
  - composer self-update

install:
  - composer install --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml
